Store decode notes
PIVX-Labs/pivx-shielding pull request #2
Opened 2023-03-09 14:19 UTC by panleone

Abstract:
This PR will add the feature of storing, decoding  and checking if a note is spent

2023-03-09 14:26 UTC, Duddino requested changes

2023-03-09 14:26 UTC, Duddino commented on src/checkpoint.rs
> +fn get_checkpoint(block_height: i32, is_testnet: bool) -> (i32, &'static str) {
```suggestion
fn get_checkpoint(block_height: i32, is_testnet: bool) -> Option<(i32, &'static str)> {
```
Change this to an option so we don't have to panic if there is no available checkpoint

2023-03-09 14:26 UTC, Duddino commented on src/checkpoint.rs
> +    return used_checkpoints.iter().rev().filter(|x| { x.0 < block_height}).next().unwrap().clone();
```suggestion
    return used_checkpoints.iter().rev().filter(|x| { x.0 < block_height}).next().clone();
```

2023-03-09 14:26 UTC, Duddino commented on src/lib.rs
> +use pivx_client_backend::keys::{sapling, UnifiedFullViewingKey}; //::{decode_extended_spending_key, decode_transparent_address};
Remove the comment

2023-03-09 14:26 UTC, Duddino commented on src/lib.rs
> +    block_data: String,
```suggestion
    block_data: &str,
```
Change to &str so we don't have to use the owned data type

2023-03-09 14:26 UTC, Duddino commented on src/lib.rs
> +) -> Vec<(Note, MerklePath<Node>)> {
```suggestion
) -> Result<Vec<(Note, MerklePath<Node>)>, Box<dyn Error>> {
```

2023-03-11 10:25 UTC, panleone commented
Ready for review

2023-03-11 12:29 UTC, Duddino requested changes
I like the logic, but there are some styling issues.
Also run cargo fmt

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +        let mut buff = Cursor::new(Vec::new());
```suggestion
        let mut buff = Vec::new();
```
Cursor is not needed

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +    for x in comp_note.iter() {
```suggestion
    for (note, witness) in comp_note.iter() {
```

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +        let newNote = x.0.clone();
```suggestion

```

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +        ser_comp_note.push((newNote, hex::encode(&buff.into_inner())));
```suggestion
        ser_comp_note.push((note.clone(), hex::encode(&buff.into_inner())));
```

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +    let mut buff = Cursor::new(Vec::new());
```suggestion
    let mut buff = Vec::new();
```

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +pub fn remove_unspent_notes(
```suggestion
pub fn remove_spent_notes(
```
Typo

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +    for x in hex_notes.iter() {
Destructor this same as above

2023-03-11 12:29 UTC, Duddino commented on src/lib.rs
> +    for x in notes.iter() {
Destructure this

2023-03-11 12:46 UTC, panleone commented on src/lib.rs
> +    return serde_wasm_bindgen::to_value(&get_checkpoint(block_height, is_testnet).unwrap())
I will fix this on the Checkpoint PR

2023-03-11 13:10 UTC, panleone commented
Suggestion should be fixed now

2023-03-11 13:16 UTC, Duddino approved these changes
tACK

2023-03-11 13:17 UTC, merged