Various bug fixes
PIVX-Labs/pivx-shielding pull request #26
Opened 2023-03-18 08:24 UTC by panleone

Solve a couple of bug found during testing:

- Use an appropriate INTERNAL change address when generating a shield tx
- Fix a bug in finalizeTransaction
- Fix documentation for the list of unspent notes

2023-03-19 19:54 UTC, panleone commented
Soo I kept testing the full Shield system on MPW and I found another couple of problems: the main one is that internal change address is completely broken and any PIVs sent there are lost forever, so we should switch back to a normal shield address  for changes,

2023-03-22 08:18 UTC, Duddino requested changes

2023-03-22 08:18 UTC, Duddino commented on src/keys.rs
> +            if !(enc_addr == last_addres) {
```suggestion
            if enc_addr != last_addres {
```

2023-03-22 08:18 UTC, Duddino commented on src/transaction.rs
> +    let mut amount = amount;
```suggestion
```
Remove this line and add mut in the parameters

2023-03-22 09:09 UTC, Duddino commented on src/keys.rs
>      loop {
Deferred to #30

2023-03-22 09:10 UTC, Duddino approved these changes
tACK other than the typo

2023-03-22 09:10 UTC, Duddino commented on src/keys.rs
> +        let bundle_adress = extsk
typo

2023-03-22 09:19 UTC, merged