Shield Database
PIVX-Labs/pivx-shielding pull request #41
Opened 2023-03-27 19:43 UTC by panleone

Add a standard way to export and import shieldData

2023-03-27 20:22 UTC, panleone commented
ready for review! I'm updating MPW so testing become easier

2023-03-28 09:20 UTC, Duddino requested changes
Good work, but as always I have my nitpicks :smiley:

2023-03-28 09:20 UTC, Duddino commented on js/pivx_shielding.js
> +        console.log("Successfully read database!");
```suggestion
```

2023-03-28 09:20 UTC, Duddino commented on js/pivx_shielding.js
> +    sanityAddress,
Sanity address doesn't mean anything to me, maybe call it default address?

2023-03-28 09:20 UTC, Duddino commented on js/pivx_shielding.js
> +export class ShieldDB {
I don't really like this name, this is not a database, it shouldn't be called DB

2023-03-28 12:48 UTC, Duddino commented on js/pivx_shielding.js
> +    const { defAddress, _ } = await this.callWorker(
```suggestion
    const { address, _ } = await this.callWorker(
```

2023-03-28 13:00 UTC, panleone commented
suggestion fixed

2023-03-28 14:06 UTC, Duddino approved these changes
tACK

2023-03-28 14:07 UTC, merged